application: homework8
version: 1
runtime: php55
threadsafe: yes
api_version: 1
handlers:
- url: /bingSearch.php
  script: bingSearch.php

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /down.png
  static_files: down.png
  upload: down.png

- url: /logo.png
  static_files: logo.png
  upload: logo.png

- url: /markit.png
  static_files: markit.png
  upload: markit.png

- url: /mod-logo.png
  static_files: mod-logo.png
  upload: mod-logo.png

- url: /script.js
  static_files: script.js
  upload: script.js
  
- url: /style.css
  static_files: style.css
  upload: style.css

- url: /up.png
  static_files: up.png
  upload: up.png

- url: /background.png
  static_files: background.png
  upload: background.png